//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBAKERYPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAMDIKEM
    {
        public int MASPK { get; set; }
        public Nullable<int> MaCTSPK { get; set; }
        public Nullable<int> MACTDH { get; set; }
    
        public virtual CHITIETDIKEM CHITIETDIKEM { get; set; }
        public virtual CHITIETDONHANG CHITIETDONHANG { get; set; }
    }
}
